from .common import *

def main():
 a=argparse.ArgumentParser(); a.add_argument('--protocol',required=True); a.add_argument('--phase1-dir'); a.add_argument('--out-dir',required=True); a.add_argument('--research-sha',default='UNKNOWN'); a.add_argument('--core-sha',default='UNKNOWN'); a.add_argument('--workflow-run-id',default='LOCAL'); a.add_argument('--preflight-only',action='store_true'); z=a.parse_args()
 pp=Path(z.protocol); p=json.loads(pp.read_text()); out=Path(z.out_dir); out.mkdir(parents=True,exist_ok=True)
 assert p['study_id']=='USDJPY-PORTFOLIO-LOSS-CLUSTER-PHASE2-V1' and p['hypothesis_id']=='USDJPY-HYP-027' and p['candidate_id']==CANDIDATE and p['candidate_threshold']==2 and p['status']=='FROZEN_BEFORE_PHASE2_CONFIRMATION' and p['no_retuning'] and p['comparison_set']==['UNCHANGED_B02_F05_BASELINE',CANDIDATE]
 if z.preflight_only:
  dump(out/'preflight_result.json',{'status':'PASS_NO_OUTCOMES','candidate_id':CANDIDATE,'candidate_threshold':2,'comparison_count':2,'outcomes_computed':False,'MT4_accessed':False,'2025H1_accessed':False,'2025H2_accessed':False,'production_authorized':False}); return
 q=Path(z.phase1_dir)
 for f,h in p['phase1_archive_authority']['member_sha256'].items(): assert sha(q/f)==h,(f,sha(q/f),h)
 d=pd.read_csv(q/'concurrent_exposure_ledger.csv.gz'); d.entry_utc=pd.to_datetime(d.entry_utc,utc=True); d.close_utc=pd.to_datetime(d.close_utc,utc=True); d['entry_session_key']=d.entry_utc.map(sk); d['exit_session_key']=d.close_utc.map(sk); d['side_label']=np.where(d.side.astype(int)>0,'LONG','SHORT'); d['entry_month']=d.entry_utc.dt.strftime('%Y-%m')
 assert len(d)==1882 and d.trade_id.nunique()==1882
 archived=pd.read_csv(q/'counterfactual_decision_audit.csv.gz'); archived=archived[archived.candidate_id==CANDIDATE]
 state,close_state=replay(d); cmp=state.merge(archived[['trade_id','accepted_weight','decision_reason','entry_utc']],on='trade_id',how='outer',validate='one_to_one',indicator=True); cmp['weight_mismatch']=cmp.allow.astype(float)!=cmp.accepted_weight; cmp['reason_mismatch']=cmp.blocking_reason!=cmp.decision_reason; cmp['entry_timestamp_mismatch']=cmp.entry_decision_utc!=cmp.entry_utc
 x=d.merge(state[['trade_id','allow','prior_realized_loss_count','session_key']],on='trade_id',validate='one_to_one'); x['candidate_pl_jpy']=x.realized_pl_jpy*x.allow.astype(float); x['delta_jpy']=x.candidate_pl_jpy-x.realized_pl_jpy; blocked=x[~x.allow].copy()
 r1=json.loads((q/'result.json').read_text()); rob=json.loads((q/'robustness_report.json').read_text()); top=next(v for v in r1['candidate_top3'] if v['representative_candidate']==CANDIDATE); event_boot=rob['candidate_event_bootstrap'][CANDIDATE]
 tables={k:slices(x,c,k) for k,c in [('fold','fold'),('strategy','strategy'),('side','side_label'),('session','session'),('month','entry_month')]}; session_boot=boot(x)
 bgp=float(x.loc[x.realized_pl_jpy>0,'realized_pl_jpy'].sum()); bgl=float(-x.loc[x.realized_pl_jpy<0,'realized_pl_jpy'].sum()); cgp=float(x.loc[x.candidate_pl_jpy>0,'candidate_pl_jpy'].sum()); cgl=float(-x.loc[x.candidate_pl_jpy<0,'candidate_pl_jpy'].sum()); bdd=dd(x,'realized_pl_jpy'); cdd=dd(x[x.allow],'candidate_pl_jpy'); top20=x[x.realized_pl_jpy>0].nlargest(20,'realized_pl_jpy'); top20loss=float(top20.loc[~top20.allow,'realized_pl_jpy'].sum())
 exact={'trade_rows':len(x),'unique_trade_ids':x.trade_id.nunique(),'B02':int((x.strategy=='B02').sum()),'F05':int((x.strategy=='F05').sum()),'LONG':int((x.side_label=='LONG').sum()),'SHORT':int((x.side_label=='SHORT').sum()),'fold_counts':{k:int(v) for k,v in x.fold.value_counts().sort_index().items()},'blocked':len(blocked),'missing':int((cmp._merge=='right_only').sum()),'extra':int((cmp._merge=='left_only').sum()),'duplicate':len(x)-x.trade_id.nunique(),'weight_mismatch':int(cmp.weight_mismatch.sum()),'reason_mismatch':int(cmp.reason_mismatch.sum()),'entry_timestamp_mismatch':int(cmp.entry_timestamp_mismatch.sum()),'future_information_violations':int(state.future_information_violation.sum())}
 eco={'baseline':{'net_jpy':float(x.realized_pl_jpy.sum()),'gross_profit_jpy':bgp,'gross_loss_jpy':bgl,'profit_factor':pf(x.realized_pl_jpy),'realized_dd_jpy':bdd,'M15_snapshot_dd_jpy':r1['baseline']['maximum_M15_snapshot_drawdown_jpy']},'candidate':{'net_jpy':float(x.candidate_pl_jpy.sum()),'gross_profit_jpy':cgp,'gross_loss_jpy':cgl,'profit_factor':pf(x.candidate_pl_jpy),'realized_dd_jpy':cdd,'M15_snapshot_dd_jpy':r1['baseline']['maximum_M15_snapshot_drawdown_jpy']-top['pooled_M15_snapshot_DD_reduction_jpy']},'delta':{'net_improvement_jpy':float(x.delta_jpy.sum()),'realized_dd_reduction_jpy':bdd-cdd,'M15_snapshot_dd_reduction_jpy':top['pooled_M15_snapshot_DD_reduction_jpy'],'avoided_gross_loss_jpy':bgl-cgl,'lost_gross_profit_jpy':bgp-cgp,'winner_retention':cgp/bgp,'top20_winner_loss_jpy':top20loss}}
 event=blocked.groupby(['fold','portfolio_event_id'],as_index=False).delta_jpy.sum().sort_values('delta_jpy',ascending=False); best_removed=float(x.delta_jpy.sum()-event.iloc[0].delta_jpy); top3_removed=float(x.delta_jpy.sum()-event.head(3).delta_jpy.sum()); m=tables['month'].set_index('value').net_improvement_jpy; pm,nm=int((m>0).sum()),int((m<0).sum()); largest_month=float(m.max()/m[m>0].sum())
 conc={}
 for k in ['fold','strategy','side','session']:
  t=tables[k]; pos=t[t.net_improvement_jpy>0]; conc[k]={'largest_positive_effect_share':None if pos.empty else float(pos.net_improvement_jpy.max()/pos.net_improvement_jpy.sum()),'largest_value':None if pos.empty else str(pos.loc[pos.net_improvement_jpy.idxmax(),'value']),'positive_effect_total_jpy':float(pos.net_improvement_jpy.sum())}
 sens=[]; base=state[['trade_id','allow']]
 for name,kw in [('close_timestamp_minus_1s',{'offset':-1}),('close_timestamp_plus_1s',{'offset':1}),('entry_before_same_timestamp_close',{'close_first':False}),('input_shuffle_seed_1',{'shuffle':1}),('input_shuffle_seed_2',{'shuffle':2})]:
  alt,_=replay(d,**kw); c=base.merge(alt[['trade_id','allow']],on='trade_id',suffixes=('_base','_alt')); sens.append({'diagnostic':name,'blocked_trades':int((~alt.allow).sum()),'decision_mismatch_vs_binding':int((c.allow_base!=c.allow_alt).sum()),'binding_effect':name=='entry_before_same_timestamp_close'})
 se=tables['strategy'].set_index('value').net_improvement_jpy.to_dict(); side=tables['side'].set_index('value').net_improvement_jpy.to_dict(); sess=tables['session'].set_index('value').net_improvement_jpy.to_dict(); g=[]
 g += [gate('canonical_trade_identity_complete',exact['trade_rows']==1882 and exact['unique_trade_ids']==1882,exact,'1882 unique canonical trades'),gate('blocked_trade_identity_complete',exact['blocked']==27 and exact['weight_mismatch']==0 and exact['reason_mismatch']==0,{'blocked':exact['blocked'],'weight_mismatch':exact['weight_mismatch'],'reason_mismatch':exact['reason_mismatch']},'27 exact blocked trades; zero mismatch'),gate('chronology_unresolved_zero',exact['entry_timestamp_mismatch']==0,exact['entry_timestamp_mismatch'],'0'),gate('lookahead_zero',exact['future_information_violations']==0,exact['future_information_violations'],'0'),gate('duplicate_state_zero',state.trade_id.nunique()==len(state),len(state)-state.trade_id.nunique(),'0'),gate('overall_net_improvement_positive',eco['delta']['net_improvement_jpy']>0,eco['delta']['net_improvement_jpy'],'>0'),gate('candidate_pf_not_below_baseline',eco['candidate']['profit_factor']>=eco['baseline']['profit_factor'],{'baseline':eco['baseline']['profit_factor'],'candidate':eco['candidate']['profit_factor']},'>=baseline'),gate('realized_dd_reduction_positive',eco['delta']['realized_dd_reduction_jpy']>0,eco['delta']['realized_dd_reduction_jpy'],'>0'),gate('M15_snapshot_dd_reduction_positive',eco['delta']['M15_snapshot_dd_reduction_jpy']>0,eco['delta']['M15_snapshot_dd_reduction_jpy'],'>0'),gate('positive_net_folds',int((tables['fold'].net_improvement_jpy>0).sum())>=3,int((tables['fold'].net_improvement_jpy>0).sum()),'>=3/4'),gate('DD_positive_folds',top['LOFO_positive_DD_folds']>=3,top['LOFO_positive_DD_folds'],'>=3/4'),gate('winner_retention',eco['delta']['winner_retention']>=.99,eco['delta']['winner_retention'],'>=.99'),gate('top20_winner_loss_zero',top20loss==0,top20loss,'0'),gate('event_bootstrap_probability_nonpositive',event_boot['probability_nonpositive']<=.05,event_boot,'<=.05'),gate('date_session_bootstrap_favorable',session_boot['probability_nonpositive']<=.05 and session_boot['ci95_jpy'][0]>0,session_boot,'P<=.05 and lower CI>0'),gate('best_event_exclusion_positive',best_removed>0,best_removed,'>0'),gate('top3_affected_loss_events_exclusion_positive',top3_removed>0,top3_removed,'>0'),gate('largest_positive_month_share',largest_month<=.25,largest_month,'<=.25')]
 g += [gate('B02_delta_nonnegative',se['B02']>=0,se['B02'],'>=0'),gate('F05_delta_nonnegative',se['F05']>=0,se['F05'],'>=0'),gate('Long_delta_nonnegative',side['LONG']>=0,side['LONG'],'>=0'),gate('Short_delta_nonnegative',side['SHORT']>=0,side['SHORT'],'>=0'),gate('positive_months_gt_negative_months',pm>nm,{'positive':pm,'negative':nm},'positive>negative'),gate('three_session_buckets_nonnegative',sum(v>=0 for v in sess.values())>=3,{'nonnegative':sum(v>=0 for v in sess.values()),'effects':sess},'>=3'),gate('fold_concentration_below_75pct',conc['fold']['largest_positive_effect_share']<=.75,conc['fold'],'<=.75'),gate('strategy_concentration_below_75pct',conc['strategy']['largest_positive_effect_share']<=.75,conc['strategy'],'<=.75'),gate('side_concentration_below_75pct',conc['side']['largest_positive_effect_share']<=.75,conc['side'],'<=.75'),gate('session_concentration_below_75pct',conc['session']['largest_positive_effect_share']<=.75,conc['session'],'<=.75')]
 failed=[v['gate'] for v in g if not v['pass']]; decision='FAIL_PHASE2_SIDE_BREADTH_SHORT_DEPENDENT' if 'Long_delta_nonnegative' in failed or 'side_concentration_below_75pct' in failed else 'FAIL_PHASE2_STRATEGY_BREADTH' if any(v in failed for v in ['B02_delta_nonnegative','F05_delta_nonnegative','strategy_concentration_below_75pct']) else 'FAIL_PHASE2_RESAMPLING_SUPPORT' if any(v in failed for v in ['event_bootstrap_probability_nonpositive','date_session_bootstrap_favorable','best_event_exclusion_positive','top3_affected_loss_events_exclusion_positive','largest_positive_month_share']) else 'FAIL_PHASE2_WINNER_DAMAGE' if any(v in failed for v in ['winner_retention','top20_winner_loss_zero']) else 'FAIL_PHASE2_NET_OR_DD_PORTABILITY' if failed else 'PASS_PHASE2_CONFIRMATION_ELIGIBLE_FOR_CORE'
 for k,t in tables.items(): t.to_csv(out/f'{k}_metrics.csv',index=False)
 state.to_csv(out/'trade_decision_ledger.csv.gz',index=False,compression='gzip'); close_state.to_csv(out/'session_state_close_ledger.csv.gz',index=False,compression='gzip'); blocked[['trade_id','fold','strategy','side_label','entry_utc','close_utc','session','entry_session_key','prior_realized_loss_count','realized_pl_jpy','delta_jpy','portfolio_event_id']].to_csv(out/'blocked_trade_ledger.csv',index=False); pd.DataFrame(sens).to_csv(out/'sensitivity_report.csv',index=False); event.to_csv(out/'affected_event_concentration.csv',index=False); dump(out/'gate_matrix.json',g)
 result={'schema_version':'usdjpy_portfolio_loss_cluster_phase2_result_v1','study_id':p['study_id'],'hypothesis_id':p['hypothesis_id'],'candidate_id':CANDIDATE,'role':'INTERNAL_CONFIRMATION_AND_IMPLEMENTATION_CONTRACT_VALIDATION','decision':decision,'failed_binding_gates':failed,'core_authorized':decision=='PASS_PHASE2_CONFIRMATION_ELIGIBLE_FOR_CORE','MT4_authorized':decision=='PASS_PHASE2_CONFIRMATION_ELIGIBLE_FOR_CORE','2025H1_authorized':False,'2025H2_authorized':False,'production_authorized':False,'research_start_sha':p['source_identity']['research_main_at_start'],'core_start_sha':p['source_identity']['core_main_at_start'],'execution_research_sha':z.research_sha,'execution_core_sha':z.core_sha,'workflow_run_id':z.workflow_run_id,'protocol_sha256':sha(pp),'phase1_exact_reproduction':exact,'economics':eco,'event_bootstrap':event_boot,'date_session_bootstrap':session_boot,'concentration':conc,'best_event_removed_net_improvement_jpy':best_removed,'top3_affected_loss_events_removed_net_improvement_jpy':top3_removed,'positive_effect_months':pm,'negative_effect_months':nm,'largest_positive_month_share':largest_month,'gate_matrix':g,'state_contract':p['exact_state_machine_contract'],'period_firewall':{'2025H1_accessed':False,'2025H2_accessed':False,'MT4_accessed':False},'stop_rule_applied':decision!='PASS_PHASE2_CONFIRMATION_ELIGIBLE_FOR_CORE','next_action':'CLOSE_HYP027_NO_CORE_MT4_OR_2025' if failed else 'FREEZE_CANDIDATE_AND_AUTHORIZE_CORE_PARITY'}; dump(out/'result.json',result)
 (out/'human_report.md').write_text(f"# USDJPY-HYP-027 SESSION_LOSS_CAP_2 Phase 2 Confirmation\n\n- Decision: `{decision}`\n- Phase 1 identity: {exact['trade_rows']}/1882; blocked {exact['blocked']}/27; mismatches 0.\n- Net improvement: JPY {eco['delta']['net_improvement_jpy']:.0f}; realized DD reduction: JPY {eco['delta']['realized_dd_reduction_jpy']:.0f}; M15 snapshot DD reduction: JPY {eco['delta']['M15_snapshot_dd_reduction_jpy']:.0f}.\n- B02: JPY {se['B02']:.0f}; F05: JPY {se['F05']:.0f}; Long: JPY {side['LONG']:.0f}; Short: JPY {side['SHORT']:.0f}.\n- Core, MT4, 2025H1/H2, production and live remain unauthorized.\n",encoding='utf-8')
 manifest={'schema_version':'usdjpy_portfolio_loss_cluster_phase2_output_manifest_v1','decision':decision,'files':{}}
 for f in sorted(out.iterdir()):
  if f.is_file() and f.name not in ['output_manifest.json','SHA256SUMS']: manifest['files'][f.name]={'bytes':f.stat().st_size,'sha256':sha(f)}
 dump(out/'output_manifest.json',manifest)
 (out/'SHA256SUMS').write_text(''.join(f'{sha(f)}  {f.name}\n' for f in sorted(out.iterdir()) if f.is_file() and f.name!='SHA256SUMS'),encoding='utf-8')
 print(json.dumps({'decision':decision,'failed_binding_gates':failed}))
if __name__=='__main__': main()
