#!/usr/bin/env python3
from __future__ import annotations
import argparse, copy, hashlib, json, shutil
from pathlib import Path
from typing import Any

def load(p:Path)->dict[str,Any]: return json.loads(p.read_text(encoding='utf-8-sig'))
def dump(p:Path,x:Any): p.parent.mkdir(parents=True,exist_ok=True); p.write_text(json.dumps(x,ensure_ascii=False,indent=2,sort_keys=True)+'\n',encoding='utf-8')
def sha(p:Path)->str:
 h=hashlib.sha256()
 with p.open('rb') as f:
  for b in iter(lambda:f.read(1<<20),b''): h.update(b)
 return h.hexdigest()
def copyf(src:Path,dst:Path): dst.parent.mkdir(parents=True,exist_ok=True); shutil.copyfile(src,dst)

def main():
 a=argparse.ArgumentParser(); a.add_argument('--root',type=Path,default=Path('.')); a.add_argument('--result-dir',type=Path,required=True); a.add_argument('--run-id',required=True); a.add_argument('--artifact-id',required=True); a.add_argument('--artifact-digest',required=True); a.add_argument('--execution-sha',required=True); z=a.parse_args(); root=z.root.resolve(); out=z.result_dir.resolve()
 r=load(out/'result.json'); p=load(root/'configs/research/usdjpy_portfolio_loss_cluster_phase2_prereg_v1.json')
 assert r['decision']=='FAIL_PHASE2_SIDE_BREADTH_SHORT_DEPENDENT' and r['phase1_exact_reproduction']['trade_rows']==1882 and r['phase1_exact_reproduction']['blocked']==27 and not r['core_authorized'] and not r['MT4_authorized'] and not r['2025H1_authorized']
 base='configs/research/'
 copies={
  'result.json':base+'usdjpy_portfolio_loss_cluster_phase2_result_v1.json',
  'fold_metrics.csv':base+'usdjpy_portfolio_loss_cluster_phase2_fold_metrics_v1.csv',
  'strategy_metrics.csv':base+'usdjpy_portfolio_loss_cluster_phase2_strategy_metrics_v1.csv',
  'side_metrics.csv':base+'usdjpy_portfolio_loss_cluster_phase2_side_metrics_v1.csv',
  'session_metrics.csv':base+'usdjpy_portfolio_loss_cluster_phase2_session_metrics_v1.csv',
  'month_metrics.csv':base+'usdjpy_portfolio_loss_cluster_phase2_month_metrics_v1.csv',
  'gate_matrix.json':base+'usdjpy_portfolio_loss_cluster_phase2_gate_matrix_v1.json',
  'sensitivity_report.csv':base+'usdjpy_portfolio_loss_cluster_phase2_sensitivity_v1.csv',
  'blocked_trade_ledger.csv':base+'usdjpy_portfolio_loss_cluster_phase2_blocked_trade_ledger_v1.csv'
 }
 for s,d in copies.items(): copyf(out/s,root/d)
 dump(root/(base+'usdjpy_portfolio_loss_cluster_phase2_state_machine_contract_v1.json'),{'schema_version':'usdjpy_portfolio_loss_cluster_phase2_state_machine_contract_v1','study_id':p['study_id'],'hypothesis_id':p['hypothesis_id'],'candidate_id':p['candidate_id'],'binding_authority':'Phase 1 evaluator behavior','contract':p['exact_state_machine_contract'],'candidate_freeze_created':False,'reason':'Research binding breadth failure'})
 dump(root/(base+'usdjpy_portfolio_loss_cluster_phase2_reproduction_receipt_v1.json'),{'schema_version':'usdjpy_portfolio_loss_cluster_phase2_reproduction_receipt_v1','study_id':p['study_id'],'phase1_release':p['phase1_archive_authority']['release_tag'],'phase1_release_asset_sha256':p['phase1_archive_authority']['release_asset_sha256'],'identity':r['phase1_exact_reproduction'],'economics':r['economics'],'status':'PASS_EXACT_PHASE1_AUTHORITY_REPRODUCED'})
 dump(root/(base+'usdjpy_portfolio_loss_cluster_phase2_period_access_receipt_v1.json'),{'schema_version':'usdjpy_portfolio_loss_cluster_phase2_period_access_receipt_v1','hypothesis_id':'USDJPY-HYP-027','research_period_accessed':['2023H1','2023H2','2024H1','2024H2'],'MT4_accessed':False,'2025H1_accessed':False,'2025H2_accessed':False,'Core_accessed_for_implementation':False,'decision':r['decision'],'stop_rule_applied':True})
 dump(root/(base+'usdjpy_portfolio_loss_cluster_phase2_core_authorization_receipt_v1.json'),{'schema_version':'usdjpy_portfolio_loss_cluster_phase2_core_authorization_receipt_v1','hypothesis_id':'USDJPY-HYP-027','candidate_id':'SESSION_LOSS_CAP_2','authorization':'DENIED_RESEARCH_BINDING_GATE_FAILURE','failed_binding_gates':r['failed_binding_gates'],'Core':False,'MT4':False,'2025H1':False,'2025H2':False,'production':False,'live':False})
 dump(root/(base+'usdjpy_portfolio_loss_cluster_phase2_execution_receipt_v1.json'),{'schema_version':'usdjpy_portfolio_loss_cluster_phase2_execution_receipt_v1','study_id':p['study_id'],'hypothesis_id':'USDJPY-HYP-027','candidate_id':'SESSION_LOSS_CAP_2','decision':r['decision'],'workflow_run_id':int(z.run_id),'execution_sha':z.execution_sha,'artifact_id':int(z.artifact_id),'artifact_digest':z.artifact_digest,'release_tag':'usdjpy-portfolio-loss-cluster-phase2-v1','phase1_trade_identity':'1882/1882','blocked_identity':'27/27','future_information_violations':0,'Core_authorized':False,'MT4_authorized':False,'2025H1_authorized':False,'2025H2_authorized':False,'production_authorized':False,'live_authorized':False})
 candidate_registry={'schema_version':'usdjpy_portfolio_loss_cluster_phase2_candidate_registry_v1','hypothesis_id':'USDJPY-HYP-027','family':'R_PORTFOLIO_LOSS_CLUSTER_CONTROL','tested_candidate':'SESSION_LOSS_CAP_2','candidate_status':'REJECTED_CLOSED','phase2_decision':r['decision'],'failed_binding_gates':r['failed_binding_gates'],'candidate_freeze':None,'Core_authorized':False,'MT4_authorized':False,'2025H1_authorized':False,'2025H2_authorized':False,'production_authorized':False,'prohibited_reuse':['threshold retuning','Long exclusion','Short-only promotion','strategy-specific threshold','session-specific threshold','2025-informed repair']}
 dump(root/(base+'usdjpy_portfolio_loss_cluster_phase2_candidate_registry_v1.json'),candidate_registry)
 status_update={'schema_version':'usdjpy_hypothesis_ledger_status_update_v1','hypothesis_id':'USDJPY-HYP-027','family_id':'R_PORTFOLIO_LOSS_CLUSTER_CONTROL','phase1_status':'COMPLETE_ONE_PHASE2_RESEARCH_CANDIDATE','phase2_status':'CLOSED','candidate_id':'SESSION_LOSS_CAP_2','decision':r['decision'],'failed_binding_gates':r['failed_binding_gates'],'evidence_refs':[base+'usdjpy_portfolio_loss_cluster_phase2_result_v1.json',base+'usdjpy_portfolio_loss_cluster_phase2_execution_receipt_v1.json','docs/research/USDJPY_PORTFOLIO_LOSS_CLUSTER_PHASE2_RESULT_V1.md'],'authorization':'NONE_NO_CORE_NO_MT4_NO_2025_NO_PRODUCTION','prohibited_reuse':candidate_registry['prohibited_reuse']}
 dump(root/(base+'usdjpy_hypothesis_ledger_status_update_v1.json'),status_update)
 program={'schema_version':'usdjpy_2023_2024_hypothesis_program_v13','supersedes':base+'usdjpy_2023_2024_hypothesis_program_v12.json','status':'HYP027_PHASE2_FAILED_SIDE_BREADTH_CLOSED','completed_hypothesis':'USDJPY-HYP-027','family_id':'R_PORTFOLIO_LOSS_CLUSTER_CONTROL','phase2_candidate':'SESSION_LOSS_CAP_2','phase2_decision':r['decision'],'failed_binding_gates':r['failed_binding_gates'],'MT4_access':False,'2025_access':False,'production_authorized':False,'next_action':'No SESSION_LOSS_CAP candidate remains. Do not retune HYP-027 from these outcomes.'}
 dump(root/(base+'usdjpy_2023_2024_hypothesis_program_v13.json'),program)
 reg_path=root/(base+'usdjpy_research_candidate_registry_v53.json'); reg=load(reg_path); reg['schema_version']='usdjpy_research_candidate_registry_v54'; reg['supersedes']=base+'usdjpy_research_candidate_registry_v53.json'; reg['status']='USDJPY_HYP027_CLOSED_NO_PORTABLE_SESSION_LOSS_CAP'; reg['active_family']=None; reg['active_hypothesis']=None; reg['current_candidate']=None; reg['candidate_ids']=[]; reg['current_open_research_question']=None; reg['hypothesis_program']=base+'usdjpy_2023_2024_hypothesis_program_v13.json'; reg['next_action']='HYP-027 is closed as FAIL_PHASE2_SIDE_BREADTH_SHORT_DEPENDENT. No candidate freeze, Core, MT4, 2025, production or live authorization. Start no replacement candidate without a separately governed new research instruction.'; reg['phase2_confirmation']={'candidate_id':'SESSION_LOSS_CAP_2','decision':r['decision'],'result':base+'usdjpy_portfolio_loss_cluster_phase2_result_v1.json','candidate_registry':base+'usdjpy_portfolio_loss_cluster_phase2_candidate_registry_v1.json','execution_receipt':base+'usdjpy_portfolio_loss_cluster_phase2_execution_receipt_v1.json','period_access_receipt':base+'usdjpy_portfolio_loss_cluster_phase2_period_access_receipt_v1.json','candidate_freeze_created':False,'Core_authorized':False,'MT4_authorized':False,'2025H1_authorized':False,'2025H2_authorized':False,'production_authorized':False}
 if 'R_PORTFOLIO_LOSS_CLUSTER_CONTROL' not in reg.get('closed_families',[]): reg.setdefault('closed_families',[]).append('R_PORTFOLIO_LOSS_CLUSTER_CONTROL')
 catalog={'hypothesis_id':'USDJPY-HYP-027','catalog':'R_PORTFOLIO_LOSS_CLUSTER_CONTROL_SESSION_LOSS_CAP_2_V1','decision':r['decision'],'scope':'The unchanged Phase 1 SESSION_LOSS_CAP_2 rule under exact evaluator semantics. No side, strategy, session or threshold exception is authorized.'}
 if not any(x.get('hypothesis_id')=='USDJPY-HYP-027' for x in reg.get('closed_hypothesis_catalogs',[])): reg.setdefault('closed_hypothesis_catalogs',[]).append(catalog)
 reg.setdefault('research_memory',{})['hypothesis_status_update']=base+'usdjpy_hypothesis_ledger_status_update_v1.json'
 for k in list(reg.get('run_authorization',{})): reg['run_authorization'][k]=False
 dump(root/(base+'usdjpy_research_candidate_registry_v54.json'),reg)
 manifest_path=root/(base+'usdjpy_research_memory_manifest_v1.json'); m=load(manifest_path); cp=m.setdefault('canonical_pointers',{}); cp.update({'current_candidate_registry':base+'usdjpy_research_candidate_registry_v54.json','hypothesis_program':base+'usdjpy_2023_2024_hypothesis_program_v13.json','hyp027_phase2_preregistration':base+'usdjpy_portfolio_loss_cluster_phase2_prereg_v1.json','hyp027_phase2_result':base+'usdjpy_portfolio_loss_cluster_phase2_result_v1.json','hyp027_phase2_result_report':'docs/research/USDJPY_PORTFOLIO_LOSS_CLUSTER_PHASE2_RESULT_V1.md','hyp027_phase2_candidate_registry':base+'usdjpy_portfolio_loss_cluster_phase2_candidate_registry_v1.json','hyp027_phase2_execution_receipt':base+'usdjpy_portfolio_loss_cluster_phase2_execution_receipt_v1.json','hyp027_phase2_period_access_receipt':base+'usdjpy_portfolio_loss_cluster_phase2_period_access_receipt_v1.json','hyp027_phase2_output_manifest':base+'usdjpy_portfolio_loss_cluster_phase2_output_manifest_v1.json','hyp027_status_update':base+'usdjpy_hypothesis_ledger_status_update_v1.json'})
 snap=m.setdefault('current_state_snapshot',{}); snap.update({'registry_status':reg['status'],'active_family':None,'active_hypothesis':None,'current_candidate':None,'current_open_research_question':None,'candidate_signal_generation_authorized':False,'candidate_outcome_evaluation_authorized':False,'MT4_parity_authorized':False,'2025_H1_authorized':False,'2025_H2_authorized':False,'next_action':reg['next_action']})
 order=m.get('mandatory_startup_read_order',[])
 for item in order:
  if item.get('path')==base+'usdjpy_research_candidate_registry_v53.json': item['path']=base+'usdjpy_research_candidate_registry_v54.json'; item['reason']='global state after HYP-027 Phase 2 closure'
  if item.get('path')==base+'usdjpy_2023_2024_hypothesis_program_v12.json': item['path']=base+'usdjpy_2023_2024_hypothesis_program_v13.json'
 existing={x.get('path') for x in order}; additions=[(base+'usdjpy_portfolio_loss_cluster_phase2_result_v1.json','binding HYP-027 Phase 2 result'),(base+'usdjpy_hypothesis_ledger_status_update_v1.json','HYP-027 lifecycle status update')]
 for path,reason in additions:
  if path not in existing: order.append({'ordinal':len(order)+1,'path':path,'reason':reason})
 for i,item in enumerate(order,1): item['ordinal']=i
 m['mandatory_startup_read_order']=order; dump(manifest_path,m)
 report=f'''# USDJPY-HYP-027 SESSION_LOSS_CAP_2 Phase 2 Confirmation\n\n## Decision\n\n`{r['decision']}`\n\nThe unchanged candidate reproduced Phase 1 exactly and improved pooled economics, but failed binding breadth. Long deteriorated by JPY 1,570, all positive side effect came from Short, and F05 explained 76.5264% of positive strategy effect.\n\n## Exact reproduction\n\n- Canonical trades: 1,882 / 1,882\n- Blocked trades: 27 / 27\n- Missing / extra / duplicate: 0 / 0 / 0\n- Decision, reason, timestamp mismatches: 0\n- Future-information violations: 0\n\n## Economics\n\n- Baseline net / PF: JPY 51,627 / 1.1377\n- Candidate net / PF: JPY 57,212 / 1.1562\n- Net improvement: JPY 5,585\n- Realized DD reduction: JPY 3,717\n- M15 snapshot DD reduction: JPY 3,717\n- Winner retention: 99.2891%\n- Top-20 winner loss: JPY 0\n\n## Breadth failure\n\n- B02 / F05 delta: +JPY 1,311 / +JPY 4,274\n- Long / Short delta: -JPY 1,570 / +JPY 7,155\n- Strategy concentration: F05 76.5264% (limit 75%)\n- Side concentration: Short 100% (limit 75%)\n\n## Authorization\n\nNo candidate freeze was created. Core implementation, Research/Core parity, MT4 2023-2024, 2025H1, 2025H2, production, and live are not authorized and were not executed.\n'''
 (root/'docs/research/USDJPY_PORTFOLIO_LOSS_CLUSTER_PHASE2_RESULT_V1.md').parent.mkdir(parents=True,exist_ok=True); (root/'docs/research/USDJPY_PORTFOLIO_LOSS_CLUSTER_PHASE2_RESULT_V1.md').write_text(report,encoding='utf-8')
 summary_files=[Path(v) for v in copies.values()]+[Path(base+'usdjpy_portfolio_loss_cluster_phase2_state_machine_contract_v1.json'),Path(base+'usdjpy_portfolio_loss_cluster_phase2_reproduction_receipt_v1.json'),Path(base+'usdjpy_portfolio_loss_cluster_phase2_period_access_receipt_v1.json'),Path(base+'usdjpy_portfolio_loss_cluster_phase2_core_authorization_receipt_v1.json'),Path(base+'usdjpy_portfolio_loss_cluster_phase2_execution_receipt_v1.json'),Path(base+'usdjpy_portfolio_loss_cluster_phase2_candidate_registry_v1.json'),Path(base+'usdjpy_hypothesis_ledger_status_update_v1.json'),Path(base+'usdjpy_2023_2024_hypothesis_program_v13.json'),Path(base+'usdjpy_research_candidate_registry_v54.json'),Path('docs/research/USDJPY_PORTFOLIO_LOSS_CLUSTER_PHASE2_RESULT_V1.md')]
 manifest={'schema_version':'usdjpy_portfolio_loss_cluster_phase2_output_manifest_v1','decision':r['decision'],'workflow_run_id':int(z.run_id),'artifact_id':int(z.artifact_id),'artifact_digest':z.artifact_digest,'release_tag':'usdjpy-portfolio-loss-cluster-phase2-v1','files':{str(x):{'bytes':(root/x).stat().st_size,'sha256':sha(root/x)} for x in summary_files}}
 dump(root/(base+'usdjpy_portfolio_loss_cluster_phase2_output_manifest_v1.json'),manifest)
 print(json.dumps({'status':'CANONICALIZED','decision':r['decision'],'files':len(summary_files)+1}))
if __name__=='__main__': main()
