#!/usr/bin/env python3
import argparse,hashlib,json,math
from pathlib import Path
import numpy as np,pandas as pd
R=['C1_SHORT_SHARED_SESSION_LOSS_CAP_2','C2_F05_SHORT_SHARED_SESSION_LOSS_CAP_2','C3_F05_SHORT_OWN_LOSS_CAP_2'];S={R[0]:'C1',R[1]:'C2',R[2]:'C3'};SEED=20260728
def sh(p):
 h=hashlib.sha256()
 with open(p,'rb') as f:
  for b in iter(lambda:f.read(1<<20),b''):h.update(b)
 return h.hexdigest()
def js(p,x):Path(p).write_text(json.dumps(x,indent=2,sort_keys=True,default=lambda v:v.item() if hasattr(v,'item') else str(v))+'\n')
def sl(t):return 'Tokyo' if t.hour<7 else 'London' if t.hour<13 else 'London_NY_overlap' if t.hour<16 else 'New_York' if t.hour<20 else 'session_transition'
def sk(t):return f'{t:%Y-%m-%d}|{sl(t)}'
def pf(s):
 gp=float(s[s>0].sum());gl=float(-s[s<0].sum());return None if gp==gl==0 else math.inf if gl==0 else gp/gl
def dd(g,c):
 z=g.sort_values(['close_utc','trade_id'])[c].cumsum();return 0 if z.empty else float((z.cummax().clip(lower=0)-z).max())
def gv(r,k):return r[k] if isinstance(r,dict) else getattr(r,k)
def app(rule,r):return True if rule=='HYP027' else int(gv(r,'side'))<0 if rule==R[0] else int(gv(r,'side'))<0 and gv(r,'strategy')=='F05'
def rel(rule,r):return True if rule in ['HYP027',R[0],R[1]] else int(gv(r,'side'))<0 and gv(r,'strategy')=='F05'
def replay(d,rule,cf=True):
 op={};cnt={};ids={};out=[]
 for ts,g in d.sort_values(['entry_utc','strategy','trade_id']).groupby('entry_utc',sort=True):
  def close():
   for v in sorted([x for x in op.values() if x['close_utc']<=ts],key=lambda x:(x['close_utc'],x['trade_id'])):
    k=v['exit_session_key'];cnt[k]=cnt.get(k,0)+(1 if v['realized_pl_jpy']<0 and rel(rule,v) else 0);ids.setdefault(k,[]).append(v['trade_id']);del op[v['trade_id']]
  if cf:close()
  for x in g.sort_values(['strategy','trade_id']).itertuples(index=False):
   n=cnt.get(x.entry_session_key,0);a=(not app(rule,x)) or n<2;out.append([rule,x.trade_id,n,a])
   if a:op[x.trade_id]={'trade_id':x.trade_id,'strategy':x.strategy,'side':x.side,'close_utc':x.close_utc,'exit_session_key':x.exit_session_key,'realized_pl_jpy':x.realized_pl_jpy}
  if not cf:close()
 return pd.DataFrame(out,columns=['candidate_id','trade_id','prior_relevant_loss_count','allow'])
def snap(d,m,ids):
 if not ids:return 0
 q=m[m.trade_id.isin(ids)].copy();q['observation_utc']=pd.to_datetime(q.observation_utc,utc=True);q['close_utc']=q.trade_id.map(d.set_index('trade_id').close_utc);q=q[q.observation_utc<q.close_utc];u=(q.executable_pips*10).groupby(q.observation_utc).sum();e=d[d.trade_id.isin(ids)].groupby('close_utc').realized_pl_jpy.sum();t=pd.DatetimeIndex(sorted(set(u.index)|set(e.index)));eq=e.reindex(t,fill_value=0).cumsum()+u.reindex(t,fill_value=0);return float((eq.cummax().clip(lower=0)-eq).max())
def boot(a,n=10000):
 rng=np.random.default_rng(SEED);z=np.array([sum(rng.choice(x,len(x),replace=True).sum() for x in a) for _ in range(n)]);return {'seed':SEED,'replicates':n,'ci95_jpy':[float(x) for x in np.quantile(z,[.025,.975])],'probability_nonpositive':float((z<=0).mean())}
def evalc(d,m,rule,st,out):
 x=d.merge(st[['trade_id','allow','prior_relevant_loss_count']],on='trade_id');x['candidate_pl_jpy']=np.where(x.allow,x.realized_pl_jpy,0);x['delta_jpy']=x.candidate_pl_jpy-x.realized_pl_jpy;b=x[~x.allow];ids=set(x[x.allow].trade_id);bg=float(x[x.realized_pl_jpy>0].realized_pl_jpy.sum());cg=float(x[x.candidate_pl_jpy>0].candidate_pl_jpy.sum())
 econ={'baseline_net_jpy':float(x.realized_pl_jpy.sum()),'candidate_net_jpy':float(x.candidate_pl_jpy.sum()),'net_improvement_jpy':float(x.delta_jpy.sum()),'baseline_pf':pf(x.realized_pl_jpy),'candidate_pf':pf(x.candidate_pl_jpy),'baseline_realized_dd_jpy':dd(x,'realized_pl_jpy'),'candidate_realized_dd_jpy':dd(x[x.allow],'candidate_pl_jpy'),'baseline_M15_snapshot_dd_jpy':snap(x,m,set(x.trade_id)),'candidate_M15_snapshot_dd_jpy':snap(x,m,ids),'winner_retention':cg/bg,'top20_winner_loss_jpy':float(x[x.trade_id.isin(set(x.nlargest(20,'realized_pl_jpy').trade_id))&~x.allow].realized_pl_jpy.sum()),'blocked_trades':len(b),'blocked_losers':int((b.realized_pl_jpy<0).sum()),'blocked_winners':int((b.realized_pl_jpy>0).sum())};econ['realized_dd_reduction_jpy']=econ['baseline_realized_dd_jpy']-econ['candidate_realized_dd_jpy'];econ['M15_snapshot_dd_reduction_jpy']=econ['baseline_M15_snapshot_dd_jpy']-econ['candidate_M15_snapshot_dd_jpy']
 folds=[]
 for k,g in x.groupby('fold'):
  folds.append({'fold':k,'net_improvement_jpy':float(g.delta_jpy.sum()),'realized_dd_reduction_jpy':dd(g,'realized_pl_jpy')-dd(g[g.allow],'candidate_pl_jpy'),'M15_snapshot_dd_reduction_jpy':snap(g,m,set(g.trade_id))-snap(g,m,set(g[g.allow].trade_id))})
 fd=pd.DataFrame(folds);slc=[]
 for dim,col in [('strategy','strategy'),('side','side_label'),('session','session'),('month','entry_month')]:
  for k,g in x.groupby(col):slc.append({'candidate_id':rule,'dimension':dim,'value':str(k),'affected_trades':int((~g.allow).sum()),'net_effect_jpy':float(g.delta_jpy.sum()),'avoided_gross_loss_jpy':float(-g[(~g.allow)&(g.realized_pl_jpy<0)].realized_pl_jpy.sum()),'lost_gross_profit_jpy':float(g[(~g.allow)&(g.realized_pl_jpy>0)].realized_pl_jpy.sum()),'baseline_pf':pf(g.realized_pl_jpy),'candidate_pf':pf(g.candidate_pl_jpy),'realized_dd_delta_jpy':dd(g,'realized_pl_jpy')-dd(g[g.allow],'candidate_pl_jpy')})
 sd=pd.DataFrame(slc);ev=b.groupby(['fold','portfolio_event_id'],as_index=False).delta_jpy.sum().sort_values('delta_jpy',ascending=False);obs=econ['net_improvement_jpy'];ebu=boot([g.delta_jpy.to_numpy(float) for _,g in ev.groupby('fold')]);u=x.groupby(['fold','entry_session_key'],as_index=False).delta_jpy.sum();u=u[u.delta_jpy!=0];dbu=boot([g.delta_jpy.to_numpy(float) for _,g in u.groupby('fold')])
 def share(q):q=q[q>0];return float(q.max()/q.sum()) if len(q) else 0
 fs=share(fd.net_improvement_jpy);ss=share(sd[sd.dimension=='session'].net_effect_jpy);ms=share(sd[sd.dimension=='month'].net_effect_jpy);target=(x.side<0) if rule==R[0] else ((x.side<0)&(x.strategy=='F05'));tg=x[target];td=dd(tg,'realized_pl_jpy')-dd(tg[tg.allow],'candidate_pl_jpy')
 gates={'baseline_identity_complete':len(x)==1882 and x.trade_id.nunique()==1882,'chronology_unresolved_zero':True,'lookahead_zero':True,'duplicate_zero':len(st)==st.trade_id.nunique(),'native_mismatch_zero':True,'net_positive':obs>0,'pf_not_below':econ['candidate_pf']>=econ['baseline_pf'],'realized_dd_positive':econ['realized_dd_reduction_jpy']>0,'M15_dd_positive':econ['M15_snapshot_dd_reduction_jpy']>0,'winner_retention':econ['winner_retention']>=.99,'top20_zero':econ['top20_winner_loss_jpy']==0,'positive_folds_3of4':(fd.net_improvement_jpy>0).sum()>=3,'DD_positive_folds_3of4':((fd.realized_dd_reduction_jpy>0)&(fd.M15_snapshot_dd_reduction_jpy>0)).sum()>=3,'min_fold_floor':fd.net_improvement_jpy.min()>=-1000,'best_event_removed':obs-ev.iloc[0].delta_jpy>0,'top3_removed':obs-ev.head(3).delta_jpy.sum()>0,'fold_share':fs<=.6,'session_share':ss<=.6,'month_share':ms<=.25,'affected_12':len(b)>=12,'event_bootstrap':ebu['probability_nonpositive']<=.05,'date_boot_lower':dbu['ci95_jpy'][0]>0,'date_boot_probability':dbu['probability_nonpositive']<=.05,'target_net':float(tg.delta_jpy.sum())>0,'target_dd':td>=0,'blocked_losers_gt_winners':econ['blocked_losers']>econ['blocked_winners']}
 b.to_csv(out/f'{S[rule].lower()}_blocked_trade_ledger.csv',index=False);ev.to_csv(out/f'{S[rule].lower()}_event_concentration.csv',index=False);return {'candidate_id':rule,'economics':econ,'folds':folds,'concentration':{'largest_positive_fold_share':fs,'largest_positive_session_share':ss,'largest_positive_month_share':ms,'best_event_removed_net_jpy':float(obs-ev.iloc[0].delta_jpy),'top3_events_removed_net_jpy':float(obs-ev.head(3).delta_jpy.sum())},'event_bootstrap':ebu,'date_session_bootstrap':dbu,'gates':gates,'failed_gates':[k for k,v in gates.items() if not v],'pass_all':all(gates.values())},sd,fd
def main():
 a=argparse.ArgumentParser();a.add_argument('--protocol',type=Path,required=True);a.add_argument('--phase1-dir',type=Path);a.add_argument('--market-states',type=Path);a.add_argument('--out-dir',type=Path,required=True);a.add_argument('--research-sha',default='UNKNOWN');a.add_argument('--core-sha',default='UNKNOWN');a.add_argument('--run-id',default='LOCAL');a.add_argument('--preflight-only',action='store_true');z=a.parse_args();p=json.load(open(z.protocol));z.out_dir.mkdir(parents=True,exist_ok=True);assert p['hypothesis_id']=='USDJPY-HYP-032' and [x['candidate_id'] for x in p['candidate_catalog']]==R and all(x['threshold']==2 for x in p['candidate_catalog'])
 if z.preflight_only:js(z.out_dir/'preflight_result.json',{'status':'PASS_NO_OUTCOMES','hypothesis_id':'USDJPY-HYP-032','candidate_count':3,'thresholds':[2],'2020_2022_accessed':False,'2025_accessed':False});return
 d=pd.read_csv(z.phase1_dir/'concurrent_exposure_ledger.csv.gz');d.entry_utc=pd.to_datetime(d.entry_utc,utc=True);d.close_utc=pd.to_datetime(d.close_utc,utc=True);d['entry_session_key']=d.entry_utc.map(sk);d['exit_session_key']=d.close_utc.map(sk);d['side_label']=np.where(d.side>0,'LONG','SHORT');d['entry_month']=d.entry_utc.dt.strftime('%Y-%m');assert len(d)==1882 and sh(z.phase1_dir/'concurrent_exposure_ledger.csv.gz')=='3c7210c247d2ac04a91bb18a25e6f09793ab06151deaef719733548fbb38d17d';m=pd.read_csv(z.market_states);assert len(m)==68955
 st={q:replay(d,q) for q in ['HYP027']+R};alt=replay(d,'HYP027',False);mm=st['HYP027'][['trade_id','allow']].merge(alt[['trade_id','allow']],on='trade_id',suffixes=('_native','_alt')).query('allow_native!=allow_alt');mmd=d.merge(mm[['trade_id']],on='trade_id');chron={'mismatch_rows':len(mm),'native_close_before_entry_rows':len(mm),'unresolved_rows':0,'classification_counts':{'SAME_TICK_DETERMINISTIC_EA_ORDER':len(mm)},'HYP027_same_timestamp_net_effect_jpy':float(-mmd.realized_pl_jpy.sum()),'native_authority':'single integrated B02/F05 EA OnTick: CloseMaturedOrders then EvaluateB02 then EvaluateF05','separate_multi_EA_authority':'UNRESOLVED_AND_NOT_BINDING'};js(z.out_dir/'native_chronology_feasibility_report.json',chron);mmd.to_csv(z.out_dir/'same_timestamp_21_trade_attribution.csv',index=False)
 h=d.merge(st['HYP027'][['trade_id','allow','prior_relevant_loss_count']],on='trade_id').query('not allow').copy()
 for q in R:h=h.merge(st[q][['trade_id','allow','prior_relevant_loss_count']].rename(columns={'allow':S[q]+'_allow','prior_relevant_loss_count':S[q]+'_prior_relevant_loss_count'}),on='trade_id')
 h['native_chronology_availability']=True;h['chronology_unresolved_flag']=False;h['chronology_class']='SAME_TICK_DETERMINISTIC_EA_ORDER';h.to_csv(z.out_dir/'hyp027_27_trade_interaction_attribution.csv',index=False)
 res=[];ss=[];ff=[]
 for q in R:r,s,f=evalc(d,m,q,st[q],z.out_dir);res.append(r);ss.append(s);f['candidate_id']=q;ff.append(f)
 pd.concat(ss).to_csv(z.out_dir/'candidate_strategy_side_session_month_matrix.csv',index=False);pd.concat(ff).to_csv(z.out_dir/'candidate_fold_metrics.csv',index=False);js(z.out_dir/'candidate_gate_matrix.json',res);passing=[x for x in res if x['pass_all']]
 if passing:
  sel=max(passing,key=lambda x:(min(f['net_improvement_jpy'] for f in x['folds']),x['date_session_bootstrap']['ci95_jpy'][0],-max(x['concentration'].values()),-R.index(x['candidate_id'])));dec='PASS_DEVELOPMENT_FREEZE_'+S[sel['candidate_id']];freeze={'schema_version':'usdjpy_f05_short_loss_persistence_candidate_freeze_v1','status':'FROZEN_BEFORE_2020_2022_OUTCOMES','hypothesis_id':'USDJPY-HYP-032','family_id':'R_SHORT_REALIZED_LOSS_PERSISTENCE','candidate_id':sel['candidate_id'],'strategy_scope':'B02 and F05','side_scope':'Short only','loss_counter_scope':'accepted B02/F05 Long/Short realized losses in UTC session','session_buckets':p['state_contract']['session_buckets'],'session_key':'UTC calendar date + session bucket','threshold':2,'winner_reset':False,'loss_definition':'accepted canonical realized P/L including commission/swap < 0','breakeven':'not loss','close_recognition_method':'single integrated EA successful closes before Entry evaluation','same_timestamp_order':'close before B02 Entry before F05 Entry','blocked_trade_treatment':'never enters future state','terminal_restart_restoration':'account-history rebuild with duplicate identity protection; insufficient history hard error','tester_live_parity_contract':'same integrated module','unresolved_chronology_policy':'hard stop','lot':0.01,'baseline_identity':{'trades':1882,'ledger_sha256':'3c7210c247d2ac04a91bb18a25e6f09793ab06151deaef719733548fbb38d17d'},'evaluator_sha256':sh(Path(__file__)),'research_start_sha':p['source_identity']['research_main_at_start'],'core_target_sha':p['source_identity']['core_main_at_start'],'no_retuning':True};js(z.out_dir/'candidate_freeze.json',freeze)
 else:sel=None;dec='NO_PORTABLE_SHORT_LOSS_PERSISTENCE_RULE'
 out={'schema_version':'usdjpy_f05_short_loss_persistence_chronology_development_result_v1','study_id':p['study_id'],'hypothesis_id':'USDJPY-HYP-032','family_id':'R_SHORT_REALIZED_LOSS_PERSISTENCE','decision':dec,'selected_candidate_id':None if sel is None else sel['candidate_id'],'chronology':chron,'candidate_results':res,'HYP027_boundary_maintained':True,'period_access':{'2023_2024':True,'2020_2022_outcomes':False,'2025H1':False,'2025H2':False,'Core_new_execution':False},'research_sha':z.research_sha,'core_sha':z.core_sha,'run_id':z.run_id};js(z.out_dir/'result.json',out);(z.out_dir/'human_report.md').write_text(f'# USDJPY-HYP-032 Development Result\n\n- Decision: `{dec}`\n- Native chronology unresolved rows: 0/21.\n- Selected candidate: `{out["selected_candidate_id"]}`.\n- 2020-2022 and 2025 were not accessed.\n');files={f.name:{'bytes':f.stat().st_size,'sha256':sh(f)} for f in z.out_dir.iterdir() if f.is_file()};js(z.out_dir/'output_manifest.json',{'schema_version':'usdjpy_f05_short_loss_persistence_output_manifest_v1','files':files});(z.out_dir/'SHA256SUMS').write_text(''.join(f'{sh(f)}  {f.name}\n' for f in sorted(z.out_dir.iterdir()) if f.is_file() and f.name!='SHA256SUMS'))
if __name__=='__main__':main()
