#!/usr/bin/env python3
from __future__ import annotations
import argparse,csv,hashlib,json,os
from pathlib import Path
WORK_ID='USDJPY-DATA-2020-2022-TICK-AUTHORITY-001'
MANDATORY=['collection_manifest.json','source_identity.json','raw_asset_catalog.csv','normalized_asset_catalog.csv','tick_quality_summary.json','tick_quality_by_month.csv','gap_catalog.csv','spread_distribution_by_month.csv','bar_reconstruction_receipt.json','schema_compatibility_2020_2024.json','rakuten_history_availability.json','period_role_receipt.json','release_manifest.json','sha256sums.txt','final_result.json','human_report.md']
def sha(p):
 h=hashlib.sha256();
 with p.open('rb') as f:
  for b in iter(lambda:f.read(1024*1024),b''):h.update(b)
 return h.hexdigest()
def wj(p,o):p.write_text(json.dumps(o,indent=2,sort_keys=True,ensure_ascii=False)+'\n',encoding='utf-8')
def wc(p,fields,rows):
 with p.open('w',newline='',encoding='utf-8') as f:
  w=csv.DictWriter(f,fieldnames=fields,lineterminator='\n');w.writeheader();w.writerows(rows)
def load_receipts(root):
 out=[]
 for p in root.rglob('USDJPY_DUKASCOPY_RECEIPT_*.json'):
  o=json.loads(p.read_text(encoding='utf-8'));o['_path']=str(p);out.append(o)
 return sorted(out,key=lambda x:(x['year'],x['month']))
def expected_keys():return [(2019,m) for m in (10,11,12)]+[(y,m) for y in (2020,2021,2022) for m in range(1,13)]
def aggregate(args):
 out=Path(args.out);out.mkdir(parents=True,exist_ok=True);rs=load_receipts(Path(args.receipts_root));found={(r['year'],r['month']) for r in rs};missing=[f'{y}-{m:02d}' for y,m in expected_keys() if (y,m) not in found]
 payload=[]
 for r in rs:
  for a in r['assets']:
   remote=next((x for x in r.get('remote_release_assets',[]) if x.get('name')==a['name']),{})
   payload.append({**a,'year':r['year'],'month':r['month'],'period_role':r['period_role'],'release_asset_id':remote.get('id'),'release_asset_url':remote.get('browser_download_url'),'readback_status':remote.get('readback_status'),'readback_sha256':remote.get('readback_sha256'),'readback_bytes':remote.get('readback_bytes')})
 analysis=[r for r in rs if r['period_role']=='ANALYSIS_PERIOD'];warm=[r for r in rs if r['period_role']=='WARMUP_ONLY']
 total=sum(r['quality']['tick_count'] for r in analysis);by_year={str(y):sum(r['quality']['tick_count'] for r in analysis if r['year']==y) for y in (2020,2021,2022)}
 invalid=sum(r['quality']['ask_less_than_bid_count']+r['quality']['negative_spread_count']+r['quality']['zero_or_negative_price_count']+r['quality']['out_of_order_count'] for r in analysis)
 crit=sum(r['quality']['critical_gap_count'] for r in analysis);terminal=sum(r['quality']['error_hours'] for r in rs)
 hard_fail=bool(missing or terminal or invalid or any(r['decision'].startswith('FAIL') for r in rs))
 decision='FAIL_INCOMPLETE_SOURCE_COVERAGE' if (missing or terminal) else ('FAIL_SCHEMA_OR_PRICE_INTEGRITY' if hard_fail else ('PASS_WITH_DOCUMENTED_SOURCE_GAPS' if crit else 'PASS_2020_2022_TICK_AUTHORITY_CERTIFIED'))
 collection={'schema_version':'usdjpy_2020_2022_tick_authority_collection_manifest_v1','work_id':WORK_ID,'repository':args.repository,'source_sha':args.source_sha,'workflow_run_id':int(args.run_id),'workflow_run_attempt':int(args.run_attempt),'release_tag':args.release_tag,'periods':{'warmup':{'start':'2019-10-01T00:00:00Z','end':'2019-12-31T23:59:59.999999Z','role':'WARMUP_ONLY'},'analysis':{'start':'2020-01-01T00:00:00Z','end':'2022-12-31T23:59:59.999999Z','role':'ANALYSIS_PERIOD'}},'expected_months':39,'received_months':len(rs),'missing_months':missing,'months':[{'year':r['year'],'month':r['month'],'period_role':r['period_role'],'decision':r['decision'],'tick_count':r['quality']['tick_count'],'first_timestamp_utc':r['quality']['first_timestamp_utc'],'last_timestamp_utc':r['quality']['last_timestamp_utc'],'critical_gap_count':r['quality']['critical_gap_count']} for r in rs]};wj(out/'collection_manifest.json',collection)
 source={'schema_version':'usdjpy_tick_source_identity_v1','work_id':WORK_ID,'primary_authority':{'vendor':'Dukascopy','source_identifier':'datafeed.dukascopy.com BI5','url_template':'https://datafeed.dukascopy.com/datafeed/USDJPY/{year}/{zero_based_month}/{day}/{hour}h_ticks.bi5','symbol':'USDJPY','timezone':'UTC','record_layout':'>IIIff','price_scale':1000.0,'orientation':'ask_raw then bid_raw; normalized bid then ask','timestamp_precision':'milliseconds source; ISO-8601 microsecond field','pip_definition':'0.01 JPY','raw_payload_preserved':True},'collection_tool':{'downloader':'tools/download_dukascopy_raw_tick_day_v1.py','authority_builder':'tools/build_usdjpy_2020_2022_tick_authority_month_v1.py','source_sha':args.source_sha,'workflow_run_id':int(args.run_id)},'not_rakuten_quote_equivalence':True};wj(out/'source_identity.json',source)
 raw=[p for p in payload if p['layer']=='raw'];norm=[p for p in payload if p['layer']=='normalized'];bars=[p for p in payload if p['layer']=='bars']
 fields=['year','month','period_role','name','bytes','sha256','release_asset_id','release_asset_url','readback_status','readback_bytes','readback_sha256']
 wc(out/'raw_asset_catalog.csv',fields,[{k:a.get(k) for k in fields} for a in raw]);wc(out/'normalized_asset_catalog.csv',fields,[{k:a.get(k) for k in fields} for a in norm])
 qfields=['year','month','period_role','decision','tick_count','first_timestamp_utc','last_timestamp_utc','resolved_hours','downloaded_hours','missing_404_hours','no_tick_hours','error_hours','download_retry_attempts','duplicate_timestamp_count','complete_duplicate_row_count','ask_less_than_bid_count','zero_spread_count','negative_spread_count','zero_or_negative_price_count','abnormal_spread_count','price_jump_over_50_pips_count','gap_over_15m_count','critical_gap_count','weekend_tick_count','raw_to_normalized_rows_match','normalized_to_bar_tick_counts_match']
 qrows=[]
 for r in rs:
  q=r['quality'];qrows.append({k:(r.get(k) if k in ('year','month','period_role','decision') else q.get(k)) for k in qfields})
 wc(out/'tick_quality_by_month.csv',qfields,qrows)
 spreads=[r['spread_distribution']|{'period_role':r['period_role']} for r in rs];sf=['year','month','period_role','tick_count','min_spread_pips','max_spread_pips','mean_spread_pips','p50_spread_pips_approx','p90_spread_pips_approx','p95_spread_pips_approx','p99_spread_pips_approx','p999_spread_pips_approx','abnormal_threshold_pips','abnormal_spread_count','sample_size'];wc(out/'spread_distribution_by_month.csv',sf,[{k:s.get(k) for k in sf} for s in spreads])
 gaps=[]
 for r in rs:
  q=r['quality'];
  if q['critical_gap_count']:
   gaps.append({'year':r['year'],'month':r['month'],'period_role':r['period_role'],'critical_gap_count':q['critical_gap_count'],'monthly_qc_asset':next(a['name'] for a in r['assets'] if a['layer']=='quality'),'classification':'DETAILED_ROWS_IN_MONTHLY_QC_ASSET'})
 wc(out/'gap_catalog.csv',['year','month','period_role','critical_gap_count','monthly_qc_asset','classification'],gaps)
 quality={'schema_version':'usdjpy_tick_quality_summary_v1','work_id':WORK_ID,'decision':decision,'analysis_period_tick_count':total,'warmup_tick_count':sum(r['quality']['tick_count'] for r in warm),'year_tick_counts':by_year,'month_coverage':{'expected_analysis_months':36,'received_analysis_months':len(analysis),'expected_warmup_months':3,'received_warmup_months':len(warm),'missing_months':missing},'critical_gap_count':crit,'invalid_bid_ask_or_price_count':invalid,'terminal_download_error_hours':terminal,'all_month_timestamp_monotonic':all(r['quality']['timestamp_monotonic_non_decreasing'] for r in rs),'all_raw_to_normalized_rows_match':all(r['quality']['raw_to_normalized_rows_match'] for r in rs),'all_normalized_to_bar_tick_counts_match':all(r['quality']['normalized_to_bar_tick_counts_match'] for r in rs),'leap_day_2020_tick_count':next((r['quality']['leap_day_tick_count'] for r in rs if r['year']==2020 and r['month']==2),None),'production_authorization':False,'candidate_evaluation_executed':False};wj(out/'tick_quality_summary.json',quality)
 barrec={'schema_version':'usdjpy_bar_reconstruction_receipt_v1','work_id':WORK_ID,'timeframes':['M1','M5','M15','H1','H4','D1'],'sides':['bid','ask'],'bar_rule':'UTC epoch-aligned OHLC; first and last actual tick timestamps; source order preserved','raw_tick_authority_replaced':False,'all_months_tick_count_consistent':quality['all_normalized_to_bar_tick_counts_match'],'monthly_assets':bars};wj(out/'bar_reconstruction_receipt.json',barrec)
 compat={'schema_version':'usdjpy_tick_schema_compatibility_2020_2024_v1','work_id':WORK_ID,'authorities_compared':['usdjpy-2023-raw-bidask-ticks-v1','usdjpy-2024-raw-bidask-ticks-v1',args.release_tag],'matches':{'source':'Dukascopy BI5','symbol':'USDJPY','timezone':'UTC','price_scale':1000.0,'pip_definition':'0.01 JPY','bid_ask_orientation':'normalized bid then ask','timestamp_source_precision':'milliseconds','duplicate_policy':'preserve source order; audit, do not silently delete','raw_preservation':'hourly BI5 payloads','compression':'deterministic gzip/tar.gz','release_readback':'byte size and SHA-256'},'differences':[{'field':'normalized_schema','2023_2024':'timestamp_utc,symbol,bid,ask,bid_volume,ask_volume,source','2020_2022':'timestamp_utc,bid,ask,spread_price,spread_pips,symbol,source,source_file,year,month,trading_date_utc,sequence','impact':'backward-compatible semantic superset but not byte-schema-identical','downstream_adapter':'select or map common fields; sequence is month-scoped 1-based'},{'field':'derived_bars','2023_2024':'not part of original raw release contract','2020_2022':'M1/M5/M15/H1/H4/D1 bid and ask bars included','impact':'additive derived layer only','downstream_adapter':'none for raw readers'}],'compatible_for_source_native_analysis':True,'byte_identical_schema':False};wj(out/'schema_compatibility_2020_2024.json',compat)
 rak={'schema_version':'rakuten_history_availability_v1','work_id':WORK_ID,'decision':'RAKUTEN_RAW_TICK_NOT_AVAILABLE','broker_native_raw_bidask_tick':{'available':False,'basis':'No documented Rakuten export/API for historical broker-native Bid/Ask raw ticks was identified; existing assets are MT4 bar/tester history.'},'available_history':[{'type':'MT4_HST','symbol':'USDJPY','timeframes':['M1','M15'],'coverage':'2019-01-01 through 2022-12-31 with tester runoff to 2023-01-10','timezone':'Rakuten server UTC+2 standard / UTC+3 US-DST converted to UTC','source':'RakutenSecurities-Live terminal history','M1':{'sha256':'db00b63e9e7ff2dd3f785563ad7f392a7e79ccef8a2c3e696f662b397b2b5af0','bytes':583023988,'records':9717064},'M15':{'sha256':'b22e9fb9a6d0f397b4186ba17f6e71cae9eb38aa59f214dfd1eb5173e4e7f165','bytes':40958008,'records':682631},'raw_tick':False},{'type':'MT4_MODEL_0_FIXED_SPREAD_TESTER','model':0,'spread_points':5,'spread_pips':0.5,'source':'Rakuten HST plus MT4 tester interpolation/model contract','raw_tick':False},{'type':'DUKASCOPY_CONVERTED_PSEUDO_BROKER_HISTORY','availability':'existing separate portability/import workflows','source':'Dukascopy-derived','raw_rakuten_tick':False}],'authority_substitution_allowed':False};wj(out/'rakuten_history_availability.json',rak)
 period={'schema_version':'usdjpy_period_role_receipt_v1','work_id':WORK_ID,'roles':{'2019-10-01_2019-12-31':'WARMUP_ONLY','2020-01-01_2022-12-31':'ANALYSIS_PERIOD','2023-01-01_2024-12-31':'RESEARCH_AND_CANDIDATE_CONSTRUCTION_PERIOD','2025H1':'VALIDATION_PERIOD'},'binding_candidate_gate_executed':False,'candidate_selection_or_retuning_executed':False,'strategy_profit_loss_computed':False,'2025_accessed':False,'production_authorization':False};wj(out/'period_role_receipt.json',period)
 release={'schema_version':'usdjpy_tick_authority_release_manifest_v1','work_id':WORK_ID,'release_tag':args.release_tag,'workflow_run_id':int(args.run_id),'workflow_run_attempt':int(args.run_attempt),'source_sha':args.source_sha,'payload_assets':payload,'required_metadata_files':MANDATORY,'immutability_contract':'NO_REUPLOAD_AFTER_FINAL_PUBLICATION','readback_complete':all(a.get('readback_status')=='PASS_BYTE_IDENTICAL_RELEASE_READBACK' for a in payload)};wj(out/'release_manifest.json',release)
 final={'schema_version':'usdjpy_2020_2022_tick_authority_final_result_v1','work_id':WORK_ID,'decision':decision,'period_role':'ANALYSIS_PERIOD','source':'Dukascopy source-native USDJPY Bid/Ask BI5','scored_period':{'start':'2020-01-01','end':'2022-12-31','role':'ANALYSIS_PERIOD','strategy_scored':False},'warmup_period':{'start':'2019-10-01','end':'2019-12-31','role':'WARMUP_ONLY'},'total_tick_count':total,'year_tick_counts':by_year,'month_coverage':quality['month_coverage'],'critical_gap_count':crit,'invalid_bid_ask_count':invalid,'raw_assets':[a for a in payload if a['layer']=='raw'],'normalized_assets':[a for a in payload if a['layer']=='normalized'],'bar_assets':[a for a in payload if a['layer']=='bars'],'all_sha256':{a['name']:a['sha256'] for a in payload},'release_tag':args.release_tag,'release_asset_ids':{a['name']:a.get('release_asset_id') for a in payload},'readback_result':'PASS_BYTE_IDENTICAL_RELEASE_READBACK' if release['readback_complete'] else 'FAIL_OR_INCOMPLETE_READBACK','rakuten_raw_tick_availability':'RAKUTEN_RAW_TICK_NOT_AVAILABLE','production_authorization':False,'candidate_evaluation_executed':False,'strategy_scoring_executed':False,'existing_formal_decisions_changed':False,'exact_next_action':'Use this authority only for preregistered regime analysis, failure decomposition, source portability analysis, and long-horizon mechanism diagnostics. Do not use it to select, retune, approve, reject, or replace any candidate or the 2025H1 validation period.'};wj(out/'final_result.json',final)
 report=f'''# USDJPY 2020–2022 Source-Native Bid/Ask Tick Authority\n\n- Work ID: `{WORK_ID}`\n- Decision: `{decision}`\n- Primary source: Dukascopy source-native USDJPY BI5\n- Analysis period: 2020-01-01 through 2022-12-31\n- Warm-up only: 2019-10-01 through 2019-12-31\n- Analysis Tick count: {total:,}\n- 2020: {by_year['2020']:,}\n- 2021: {by_year['2021']:,}\n- 2022: {by_year['2022']:,}\n- Critical gaps requiring review: {crit}\n- Invalid Bid/Ask or non-positive price rows: {invalid}\n- Release: `{args.release_tag}`\n- Workflow run: `{args.run_id}` attempt `{args.run_attempt}`\n- Rakuten broker-native raw Tick: `RAKUTEN_RAW_TICK_NOT_AVAILABLE`\n\n## Firewall\n\nThis data authority is analysis-only. No B02, F05, C3, HYP-039, HYP-040, HYP-041, HYP-042, or Common Portfolio candidate P/L was computed. Existing formal decisions and 2025H1 validation results are unchanged.\n\n## Layers\n\nThe Release preserves monthly original BI5 payloads, monthly normalized Tick CSV.GZ, Bid/Ask bars for M1/M5/M15/H1/H4/D1, monthly QC packages, root manifests, SHA-256 values, and remote readback receipts. Derived bars do not replace raw Tick authority.\n\n## Permitted next use\n\nPreregistered regime analysis, failure decomposition, source-portability diagnostics, and long-horizon mechanism stability analysis are permitted. Candidate selection, threshold tuning, side/session/holding changes, or substitution for 2025H1 validation are prohibited.\n''';(out/'human_report.md').write_text(report,encoding='utf-8')
 (out/'sha256sums.txt').write_text(''.join(f"{a['sha256']}  {a['name']}\n" for a in sorted(payload,key=lambda x:x['name'])),encoding='utf-8')
 print(json.dumps({'decision':decision,'analysis_ticks':total,'months':len(rs),'critical_gaps':crit,'missing':missing},sort_keys=True))
def enrich(args):
 out=Path(args.out);release=json.loads(Path(args.release_json).read_text(encoding='utf-8'));assets={a['name']:a for a in release['assets']}
 for name in ['release_manifest.json','final_result.json']:
  p=out/name;o=json.loads(p.read_text(encoding='utf-8'));o['release_id']=release['id'];o['release_url']=release['html_url'];o['metadata_release_asset_ids']={n:a['id'] for n,a in assets.items() if n in MANDATORY and n not in ('release_manifest.json','final_result.json','sha256sums.txt')};wj(p,o)
 lines=(out/'sha256sums.txt').read_text(encoding='utf-8')
 for p in sorted(out.iterdir()):
  if p.is_file() and p.name!='sha256sums.txt' and p.name not in {x.split('  ',1)[1] for x in lines.splitlines() if '  ' in x}:
   lines+=f'{sha(p)}  {p.name}\n'
 (out/'sha256sums.txt').write_text(lines,encoding='utf-8')
def main():
 ap=argparse.ArgumentParser();sub=ap.add_subparsers(dest='cmd',required=True)
 a=sub.add_parser('aggregate');
 for n in ('receipts_root','out','repository','source_sha','run_id','run_attempt','release_tag'):a.add_argument('--'+n.replace('_','-'),dest=n,required=True)
 e=sub.add_parser('enrich');e.add_argument('--out',required=True);e.add_argument('--release-json',required=True)
 args=ap.parse_args();aggregate(args) if args.cmd=='aggregate' else enrich(args)
if __name__=='__main__':main()
